FROM python:3.9

ENV PATH $PATH:/root/google-cloud-sdk/bin

RUN curl https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz > /tmp/google-cloud-sdk.tar.gz && \
    cd /tmp && \
    tar xzf /tmp/google-cloud-sdk.tar.gz && \
    /tmp/google-cloud-sdk/install.sh --quiet && \
    rm -rf /tmp/google-cloud-sdk.tar.gz && \
    mv /tmp/google-cloud-sdk /root/

RUN apt-get update && apt-get -y upgrade  && \
    apt-get -y autoremove && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create a new user and set the password
RUN useradd -ms /bin/bash myuser && \
    echo "myuser:mypassword" | chpasswd

# Create a new user and set the password 
RUN useradd -ms /bin/bash {{name}} && \
    echo "{{name}}:{{password}}" | chpasswd

# to login as second user: `su myuser` and then `su myseconduser` to prove we need password to login user



